{"code":11000,"index":0,"keyPattern":{"id":1},"keyValue":{"id":null},"level":"error","message":"E11000 duplicate key error collection: socialapp-Users.users index: id_1 dup key: { id: null } E11000 duplicate key error collection: socialapp-Users.users index: id_1 dup key: { id: null }","stack":"MongoServerError: E11000 duplicate key error collection: socialapp-Users.users index: id_1 dup key: { id: null }\n    at D:\\nodejs_store\\node_modules\\mongodb\\lib\\operations\\insert.js:53:33\n    at D:\\nodejs_store\\node_modules\\mongodb\\lib\\cmap\\connection_pool.js:277:25\n    at D:\\nodejs_store\\node_modules\\mongodb\\lib\\sdam\\server.js:212:17\n    at handleOperationResult (D:\\nodejs_store\\node_modules\\mongodb\\lib\\sdam\\server.js:335:20)\n    at Connection.onMessage (D:\\nodejs_store\\node_modules\\mongodb\\lib\\cmap\\connection.js:222:9)\n    at MessageStream.<anonymous> (D:\\nodejs_store\\node_modules\\mongodb\\lib\\cmap\\connection.js:63:60)\n    at MessageStream.emit (node:events:526:28)\n    at processIncomingData (D:\\nodejs_store\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:132:20)\n    at MessageStream._write (D:\\nodejs_store\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:389:12)"}
{"_message":"User validation failed","errors":{"contact.firstName":{"kind":"required","message":"Path `firstName` is required.","name":"ValidatorError","path":"firstName","properties":{"message":"Path `firstName` is required.","path":"firstName","type":"required"}},"contact.lastName":{"kind":"required","message":"Path `lastName` is required.","name":"ValidatorError","path":"lastName","properties":{"message":"Path `lastName` is required.","path":"lastName","type":"required"}}},"level":"error","message":"User validation failed: contact.lastName: Path `lastName` is required., contact.firstName: Path `firstName` is required. User validation failed: contact.lastName: Path `lastName` is required., contact.firstName: Path `firstName` is required.","stack":"ValidationError: User validation failed: contact.lastName: Path `lastName` is required., contact.firstName: Path `firstName` is required.\n    at model.Document.invalidate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\document.js:2985:32)\n    at SingleNested.Subdocument.invalidate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\types\\subdocument.js:213:12)\n    at D:\\nodejs_store\\node_modules\\mongoose\\lib\\document.js:2774:17\n    at D:\\nodejs_store\\node_modules\\mongoose\\lib\\schematype.js:1334:9\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:265:14)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:265:14)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:265:14)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:265:14)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at D:\\nodejs_store\\src\\middlewares\\error.js:6:23\n    at newFn (D:\\nodejs_store\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:265:14)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:646:15"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"Parameter \"filter\" to findOne() must be an object, got 09121212121 Parameter \"filter\" to findOne() must be an object, got 09121212121","stack":"InternalServerError: Parameter \"filter\" to findOne() must be an object, got 09121212121\n    at Controller.checkExistUser (D:\\nodejs_store\\src\\routes\\auth\\controller.js:44:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:21)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"Not Found Not Found","stack":"NotFoundError: Not Found\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:15:39)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"user not found user not found","stack":"NotFoundError: user not found\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:15:39)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"user not found user not found","stack":"NotFoundError: user not found\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:15:39)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"randomNumberGenarator is not a function randomNumberGenarator is not a function","stack":"TypeError: randomNumberGenarator is not a function\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:16:20)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"user not found user not found","stack":"NotFoundError: user not found\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:14:39)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"user is not defined user is not defined","stack":"ReferenceError: user is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:28:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Invalid atomic update value for $seeeeeet. Expected an object, received number Invalid atomic update value for $seeeeeet. Expected an object, received number","stack":"Error: Invalid atomic update value for $seeeeeet. Expected an object, received number\n    at castUpdate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:102:13)\n    at model.Query._castUpdate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\query.js:4986:10)\n    at model.Query._updateThunk (D:\\nodejs_store\\node_modules\\mongoose\\lib\\query.js:4164:27)\n    at model.Query.<anonymous> (D:\\nodejs_store\\node_modules\\mongoose\\lib\\query.js:4265:23)\n    at model.Query._wrappedThunk [as _updateOne] (D:\\nodejs_store\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:27:8)\n    at D:\\nodejs_store\\node_modules\\kareem\\index.js:334:18\n    at _next (D:\\nodejs_store\\node_modules\\kareem\\index.js:128:16)\n    at D:\\nodejs_store\\node_modules\\kareem\\index.js:555:30\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"}
{"level":"error","message":"Cannot create property 'updatedAt' on number '1' Cannot create property 'updatedAt' on number '1'","stack":"TypeError: Cannot create property 'updatedAt' on number '1'\n    at applyTimestampsToUpdate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\helpers\\update\\applyTimestampsToUpdate.js:74:31)\n    at model.Query._setTimestampsOnUpdate (D:\\nodejs_store\\node_modules\\mongoose\\lib\\helpers\\timestamps\\setupTimestamps.js:100:5)\n    at callMiddlewareFunction (D:\\nodejs_store\\node_modules\\kareem\\index.js:530:27)\n    at next (D:\\nodejs_store\\node_modules\\kareem\\index.js:79:7)\n    at Kareem.execPre (D:\\nodejs_store\\node_modules\\kareem\\index.js:108:8)\n    at Kareem.wrap (D:\\nodejs_store\\node_modules\\kareem\\index.js:315:8)\n    at model.Query._updateOne (D:\\nodejs_store\\node_modules\\kareem\\index.js:431:11)\n    at D:\\nodejs_store\\node_modules\\mongoose\\lib\\query.js:4811:19\n    at D:\\nodejs_store\\node_modules\\kareem\\index.js:40:7\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"}
{"level":"error","message":"Unauthorized Unauthorized","stack":"UnauthorizedError: Unauthorized\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:24:62)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"validateSchema is not defined validateSchema is not defined","stack":"ReferenceError: validateSchema is not defined\n    at Controller.getOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:12:7)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (D:\\nodejs_store\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (D:\\nodejs_store\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\nodejs_store\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"level":"error","message":"e is not defined e is not defined","stack":"ReferenceError: e is not defined\n    at process.<anonymous> (D:\\nodejs_store\\startup\\logging.js:15:21)\n    at process.emit (node:events:526:28)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)"}
{"_original":{"code":"567","mobile":"09123456789"},"details":[{"context":{"key":"code","label":"code","limit":4,"value":"567"},"message":"\"code\" length must be at least 4 characters long","path":["code"],"type":"string.min"}],"level":"error","message":"\"code\" length must be at least 4 characters long \"code\" length must be at least 4 characters long","stack":"ValidationError: \"code\" length must be at least 4 characters long"}
{"level":"error","message":"Invalid received code Invalid received code","stack":"BadRequestError: Invalid received code\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:8:65)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Bad Request Bad Request","stack":"BadRequestError: Bad Request\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:8:65)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Invalid received code Invalid received code","stack":"BadRequestError: Invalid received code\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:8:65)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Mobile must be at least 11 character Mobile must be at least 11 character","stack":"BadRequestError: Mobile must be at least 11 character\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:7:88)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Unauthorized Unauthorized","stack":"UnauthorizedError: Unauthorized\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:38:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Unauthorized Unauthorized","stack":"UnauthorizedError: Unauthorized\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:38:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Invalid received code Invalid received code","stack":"BadRequestError: Invalid received code\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:8:65)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Mobile must be at least 11 characters Mobile must be at least 11 characters","stack":"BadRequestError: Mobile must be at least 11 characters\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:7:88)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"Unauthorized Unauthorized","stack":"UnauthorizedError: Unauthorized\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:38:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Mobile must be at least 11 characters Mobile must be at least 11 characters","stack":"BadRequestError: Mobile must be at least 11 characters\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\validator.js:7:88)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (D:\\nodejs_store\\src\\routes\\auth\\controller.js:4:40)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)"}
{"level":"error","message":"User not found User not found","stack":"NotFoundError: User not found\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:37:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Unauthorized Unauthorized","stack":"UnauthorizedError: Unauthorized\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:38:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"User not found User not found","stack":"NotFoundError: User not found\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:37:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"User not found User not found","stack":"NotFoundError: User not found\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:37:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"Invalid code Invalid code","stack":"UnauthorizedError: Invalid code\n    at Controller.checkOtp (D:\\nodejs_store\\src\\routes\\auth\\controller.js:38:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
